[general]
import = ["~/.config/alacritty/themes/themes/nordic.toml"]

[window]
startup_mode = "Fullscreen"

[font]
normal = { family = "UbuntuMonoNerdFont" }
size = 15.0

[terminal]
shell = { program = "/bin/zsh", args = ["-c", "tmux"] }

[env]
TERM = "alacritty"
